### ISSUE TITLE
Single story opmaken

### ISSUE THREAD

**Issue by Levdbas** [basedonline/rtccella#2]
### *Task Description*
We gaan we single story opmaken in `07-layouts/_single-story.scss`

![afbeelding](https://user-images.githubusercontent.com/17764157/160106548-8e18e9dd-1a2d-47ee-8ffb-07d58499209b.png)

### *Definition of Ready (DoR)*
- [x] card-story opmaken #5 

### *Definition of Done (DoD)* 
- [x] img-container afgeronde hoeken geven
- [x] Ondertitel opmaken, icoon volgt later
- [x] share buttons opmaken, het link icoon laten we voor nu achterwegen
- [x] het "meer blok opmaken"
