### ISSUE TITLE
Opmaken home-intro block

### ISSUE THREAD

**Issue by Levdbas** [basedonline/rtccella#5]
### *Task Description*
Het verder opmaken van dit element.

![afbeelding](https://user-images.githubusercontent.com/17764157/160097542-31bdc742-4da4-4473-a82c-2d852ac24bad.png)

### *Definition of Done (DoD)* 
- [x] navigatie menu verder opmaken met default status en actieve en hover staat
- [x] vacature alert button opmaken, icoon voegen we later toe. Css graag in los component zodat we deze button kunnen hergebrukken
- [x] Responsiveness controleren
- [x] Met css grid de overlap creeren op de homepage.

**Comment by MeesMoons** [comment]
- de code voor de overlap staat nu in de styleguide.scss. 
- voor alert-button een eigen styling component gemaakt "alert-button.scss". 
iets waar ik tegen aanliep:

![image](https://user-images.githubusercontent.com/51217605/160468915-b2ac4e2e-b779-4439-ab63-d7fe2ccc2118.png)

het lukte mij niet om de text verticaal te centreren bij een medium screen size.
