### ISSUE TITLE
Footer opmaken

### ISSUE THREAD

**Issue by Levdbas** [basedonline/rtccella#6]
### *Task Description*
Verder de footer opmaken.

### *Definition of Done (DoD)* 
- [ ] social icons achtergrond weg en kleur tweaken, doe dit in `.footer__closure`
- [ ] contact iconen in footer verder opmaken. Twig file: `resources\views\partials\footer\footer-logobar.twig` indien extra classes nodig zijn.
- [ ] Iconen komen niet 100% overeen, dat is niet erg.
- [ ] Responsiveness checken.
