### ISSUE TITLE
Maken laatste vacatures blok

### ISSUE THREAD

**Issue by Levdbas** [basedonline/rtccella#7]
### *Task Description*
Het laatste vacatureblok bestaat uit de drie laatste vacatures en een notificatieblock. Deze worden in een css grid opgemaakt

### *Definition of Done (DoD)* 
- [x] maken block: latest-jobs/Laatste vacatures
- [x] In block `$context['jobs'] = latest_items_query('job', 3);` plaatsen. Als je begint met typen van de functie naam dan zou er een autocomplete moeten komen. Bij een enter/klik daarop plaatst ie de functie inclusief de juiste namespace call bovenin het bestand. Mocht dit niet werken of je komt er niet uit. Bellen :)
- [x] Uit jobs.twig de for loop halen plus de card include en plaatsen in latest-jobs.twig
- [x] Uit jobs.twig de card-job-notification.twig pakken en plaatsen in latest-jobs.twig
- [x] Doe je css grid magic hierop in het juiste scss bestand
- [x] Profit!
